stages:
  - build
  - test


test:
  stage: test
  only:
    changes:
    - "*.go"
  image: golang:1.17
  script:
   - go test .
  tags:
   - runner-1

static-analysis:
 stage: test
 only:
  changes:
  - "*.go"
 image:
  name: sonarsource/sonar-scanner-cli
  entrypoint: [""]
 variables:
 script:
  - sonar-scanner -Dsonar.projectKey=project1 -Dsonar.sources=. -Dsonar.host.url=http://gitlab.localdomain:9000 -Dsonar.login=sqp_72a7e423421ad40839524494305328c776d0da0e
 tags:
   - runner-1

build:
  stage: build
  image: docker:latest
  script:
   - docker build .
  tags:
   - runner-1
